module.exports = {
  'config': 'configure',
  'c': 'configure',
  'info': 'describe',
  'g': 'generate',
  'ls': 'list',
  'l': "list",
  'lr': 'list-roots',
  'lt': 'list-templates',
  'h': 'help',
  't': 'template',
  'output': 'outputFolder',
  'o': 'open',
  'info': 'describe',
  'd': 'describe',
  'gd': 'get-directory',
  'v': 'version',
  'ar': 'add-root',
  'at': 'add-template',
  'rr': 'remove-root',
  'rt': 'remove-template'
}
