module.exports = {
  'config': 'configure',
  'c': 'configure',
  'info': 'describe',
  'g': 'generate',
  'list': 'list-templates',
  'lr': 'list-roots',
  'h': 'help',
  't': 'template',
  'output': 'outputFolder',
  'o': 'open-project',
  'open': 'open-project',
  'info': 'describe',
  'd': 'describe',
  'gd': 'get-directory',
  'v': 'version',
  'ar': 'add-root',
  'at': 'add-template',
  'rr': 'remove-root',
  'rt': 'remove-template',
  'list-aliases': 'command-aliases',
  'list-alias': 'command-aliases',
  'get-aliases': 'command-aliases',
  'get-alias': 'command-aliases',
  'command-alias': 'command-aliases',
  'ca': 'command-aliases',
  'remove-config': 'reset-config'
}
